### ISSUE TITLE
Problem with Timeline in IE

### ISSUE THREAD

**Issue by vijayamaharaja** [tshaddix/oocharts-js#11]
I used oochart timeline chart to display the visitors to my website and it was working fine in Firefox, Chrome, etc where as in Internet explorer 6+ it's kind of messed about.
Edit: It works fine for IE 9, IE6, 7, and 8 are the browsers being problematic (as usual!)

I have attached the screen shot of it. as you can see its starting from last year (1st Dec 2012) and runs through to last month (31st July 13)
![ie-timeline-screenshot](https://f.cloud.github.com/assets/5148113/946733/45b0aa8c-033b-11e3-9653-3a6088971d36.jpg)

here is the code I have used:
<code>var timeline = new oo.Timeline(My_Profile_Id, "30d");
timeline.addMetric("ga:visitors", "Visitors");
timeline.addMetric("ga:pageviews", "Page views");
timeline.setOptions({ height : ['500'] , width : ['800'] });
timeline.draw('time',print);</code>

**Comment by tshaddix** [comment]
Oh no, an IE issue! (my favorite)

I'll take a look into why that would be happening.

**Comment by vijayamaharaja** [comment]
Thanks @tshaddix am waiting for your magics...

**Comment by tshaddix** [comment]
@vijayamaharaja 
Just to make this clear, it is IE 6, 7, and 8 that are experiencing issues?

**Comment by vijayamaharaja** [comment]
Yes my friend... Its faulty in IE 6 7 and 8.

**Comment by tshaddix** [comment]
@vijayamaharaja Sounds good. I have seen this output before with incorrect dates, so I am assuming that IE 8, 7, and 6 are not parsing something correctly. I just finished creating a windows box to test on, so I will get back to you on this.

**Comment by vijayamaharaja** [comment]
Sweat... Thanks in advance mate. :)

**Comment by tshaddix** [comment]
@vijayamaharaja , no problem. I found the issue I think: [this line](https://github.com/OOcharts/js/blob/master/oocharts.js#L254)

It seems, according to SO posts like [this](http://stackoverflow.com/questions/12687165/javascript-date-undefined-nan-in-ie8) that IE doesn't register the format `YYYY-MM-DD`. So we just need to change that line to use `YYYY/MM/DD` instead.

**Comment by tshaddix** [comment]
Woops, scratch that. We're not using the `-` to separate on parsing, I read that too quickly... I'll keep looking.

**Comment by vijayamaharaja** [comment]
@tshaddix I found the bug and have came with a solution that works for me! 

First of all, I didn't used <code>"30d"</code> for last 30 days, instead I pass actual dates with formats <code>YYYY-MM-DD</code>.

Secondly I replaced code snippet for <code>_parseDate</code> function with this:

```
var _parseDate = function(val){
    val = val.split('-');
    var yy = val[0];
    var mm = val[1];
    var dd = val[2];
    var newDate = new Date();
    newDate.setUTCFullYear(yy,mm-1,dd);
    newDate.setUTCHours(0, 0, 0, 0);
        return newDate;
    };
```

This will overcome the "Date" parsing issue in IE < 9.

**Comment by tshaddix** [comment]
@vijayamaharaja awesome! Thanks for coming up with this. So it was a problem with the date constructor in the lower versions of IE?

**Comment by vijayamaharaja** [comment]
Exactly....

**Comment by tshaddix** [comment]
@vijayamaharaja 
Okay, do you mind if I add you to the contributors list for this repo?

**Comment by vijayamaharaja** [comment]
Yes you can Tyler :)

On Tue, Aug 20, 2013 at 5:16 PM, Tyler Shaddix notifications@github.comwrote:

> @vijayamaharaja https://github.com/vijayamaharaja
> Okay, do you mind if I add you to the contributors list for this repo?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/OOcharts/js/issues/11#issuecomment-22956971
> .

## 

Cumprimentos / Best regards,

Vijay (VJ)

**Comment by tshaddix** [comment]
@vijayamaharaja 
Great! I'm going to leave this issue open until:
- The fix is pushed
- You are added to README for contributing

**Comment by tshaddix** [comment]
@vijayamaharaja 
Do you think you could fork the repo then do a pull request with your fix?

**Comment by vijayamaharaja** [comment]
Hi @tshaddix 
I think I forked and added changes to oocharts.js file. Can you make sure that I have made the changes and its saved. Am pretty new to Github! and am not sure what every actions will affect :)

**Comment by tshaddix** [comment]
@vijayamaharaja 
Sure, no problem! I will take a look at it and let you know.

**Comment by tshaddix** [comment]
@vijayamaharaja 

Your release: https://github.com/OOcharts/js/releases/tag/v0.0.7

**Comment by tshaddix** [comment]
@vijayamaharaja 

You're now added to the contributors list as well. Thanks for the help!

**Comment by vijayamaharaja** [comment]
Yeay :smile_cat: my first contribution in github

**Comment by tshaddix** [comment]
We would love to see more when you have any ideas or issues :)
