### ISSUE TITLE
Pulling data for yesterday and a week before yesterday

### ISSUE THREAD

**Issue by svgecommerce** [tshaddix/oocharts-js#19]
Hi there,
I'm trying to figure out how to create displays that show information about:
- yesterday
- 7 days before yesterday

and I'm having trouble figuring out how to get the right numbers for yesterday. I can get today with 0d and the sum of today and yesterday with 1day, but there doesn't seem to be a way to subtract and isolate yesterday. Likewise, the same overarching concept applies to 7 days before yesterday. Can you help me?

Thank you so much!
Sarah

**Comment by tshaddix** [comment]
Hey Sarah ( @svgecommerce )

In cases where the end date is not the current date, you would have to use a fixed date. Luckily, we can easily calculate what yesterday was in js:

``` js
var date = new Date();
date.setDate(date.getDate() - 1); 
//date is now set to yesterday's date
```

So using a constructor for a metric:

``` js
var yest = new Date();
yest.setDate(date.getDate() - 1); 

var oneDay = oo.Metric("your profile id", "0d", yest); //just gets results from yesterday

var sevenDays = oo.Metric("your profile id", "7d", yest); // get results from 7 days before yesterday to yesterday

```

And then you would just go on to use the `draw()` function on those metrics.
