### ISSUE TITLE
Geo chart support (or example?)

### ISSUE THREAD

**Issue by tshaddix** [tshaddix/oocharts-js#2]
@Cam suggested the ability to easily chart data on map. This has been requested before, so it is viable candidate feature in next release.

**Comment by cam** [comment]
Well that has me excited! :+1:

**Comment by tshaddix** [comment]
@Cam glad to hear it. Looks simple enough...

Basic scaffolding:

Dimension chosen by type: `regions`, `countries`, `provinces`, `states` (Check if cities will work with state region)
Metrics: Multiple can be added with label

**Comment by cam** [comment]
Awesome. Wouldn't states and regions be the same thing?

**Comment by tshaddix** [comment]
You're right. The Google documentation for metrics and geochart conflict on nomenclature:

"The region mode colorizes whole regions, such as countries, provinces, or states."

But it would make since to go with analytics nomenclature which says that a state is a region.

**Comment by cam** [comment]
Yeah I thought it was a bit odd (Google's method) too. Cool :)

**Comment by tshaddix** [comment]
Sweet! I've already added a branch to this repo for work with the Geochart. I'll begin working on that release shortly.

**Comment by cam** [comment]
Brilliant stuff! :+1:

**Comment by tshaddix** [comment]
After looking into this a little further, it seems there are a lot of option to account for. It may be better to include documentation on how to create a geo chart with a query, at least for now.

**Comment by tshaddix** [comment]
Example: https://gist.github.com/tshaddix/6288549
