### ISSUE TITLE
Get the title of Goal analytics?

### ISSUE THREAD

**Issue by rmarcou** [tshaddix/oocharts-js#20]
Hi,

Can i get the title of the Goals oanalytics with the API?

If yes, how its possible?

**Comment by tshaddix** [comment]
Hello @rmarcou,

From what I can tell, the [Google Analytics Core Reporting API](https://developers.google.com/analytics/devguides/reporting/core/v3/) that OOcharts sits in front of does not provide a way to get this information. You can use the Google Analytics Management API manually to retrieve this information, but that is outside the scope of OOcharts.

**Comment by rmarcou** [comment]
Thank you for this quick response.

**Comment by tshaddix** [comment]
@rmarcou No problem! Let me know if I can offer any more assistance.
