### ISSUE TITLE
Rotate Bar Chart or Get Google's Column Chart

### ISSUE THREAD

**Issue by jamiedewitz** [tshaddix/oocharts-js#21]
Hi I was wondering how to rotate the bar chart to show vertical columns, rather than horiczontal bars. I noticed there is no mention of Google's Column Chart here, which leads me to believe this isn't supported.

Can you tell me a way to rotate the bar chart or can you just add the capability to show the column chart so I can use it please?

**Comment by tshaddix** [comment]
Hey @jamiedewitz, I'll be happy to look into that for the next release.

**Comment by jamiedewitz** [comment]
Thanks, I'm not very skilled in js, but I'm trying to figure it out. If I can successfully add column, I'll submit it here.

**Comment by tshaddix** [comment]
@jamiedewitz glad to hear you'll look into contributing! A starting point: https://github.com/OOcharts/js/blob/master/oocharts.js#L564-L649

It should be as simple as a copy of that code with a small change in the draw function.

**Comment by tshaddix** [comment]
More specifically, a change to this line: https://github.com/OOcharts/js/blob/master/oocharts.js#L642

**Comment by jamiedewitz** [comment]
Thanks! Good to know I was looking in the right place! :)

**Comment by jamiedewitz** [comment]
HA! I did it! :dancer: 
Where do I send this to?

**Comment by tshaddix** [comment]
Awesome! We'd love to have you contribute to the repo through Github if you are familiar with that process: fork the repo, make the change, submit a pull request.

I will be happy to add you to the contributors list as well.

**Comment by jamiedewitz** [comment]
I've never contributed before so I'm not familiar with the process. Thanks for the help!

**Comment by tshaddix** [comment]
That's okay! Just fork the repo with the button at the top. Once you do that, you will have a copy of the repo under your name. Make your changes in there, and once you are done you can submit a pull request back to this repo which well allow me to merge your changes. Quick answer [here](http://stackoverflow.com/questions/4384776/how-do-i-contribute-to-others-code-in-github).

**Comment by jamiedewitz** [comment]
Ok. I hope I did that right. Similar to Tortoise SVN that we use at work, but it's always scary when you are first committing changes. lol

Thank you

**Comment by tshaddix** [comment]
Awesome! Merged. I will go ahead and minify the source and create a new release.

**Comment by tshaddix** [comment]
Okay, everything is set up! Thanks for your help @jamiedewitz 

You have been added to the contributors list as well :)

**Comment by jamiedewitz** [comment]
Yay! Sorry if I didn't do something right, I noticed you opened an issue about documentation of column charts. Was I supposed to include documentation from Google explaining how they are used?

**Comment by tshaddix** [comment]
No everything looks good! And no worries on the documentation, that's something we will handle because we have a few new things to include anyways. Thanks again!
