### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by damiansmith86** [tshaddix/oocharts-js#25]
I have linked my Google account to OOcharts and was provided with an API key.

I have added this API key, as well as my account ID but get the following error:

JSONP.callbacks.request_0 && JSONP.callbacks.request_0({"error":"Invalid param {key}: API Key is invalid"});

**Comment by tshaddix** [comment]
Hey @damiansmith86 

Quick question just to be sure: The API Key was generated in OOcharts Mission Control, correct?

**Comment by damiansmith86** [comment]
Sorry for late response, It seems to be working now, so there must have been an issue my side somewhere!

**Comment by tshaddix** [comment]
@damiansmith86 Awesome! Glad it is working now.
