### ISSUE TITLE
About setOptions

### ISSUE THREAD

**Issue by iJohnnyCash** [tshaddix/oocharts-js#29]
Hey! 

I want to change some things in appearance from charts. In first place i will use only timelines. So I need some help for setOptions, because the documentation is a little poor about this. 

Here is a first example but it doesn't work. Why?
`<script type="text/javascript">
                                window.onload = function(){
                                    oo.setAPIKey("XXXXXX");
                                    oo.setTimelineDefaults("colors : ['#FF8000', '#7FFF00', '#FF00FE']");
                                    oo.load(function(){
                                        var timeline = new oo.Timeline("XXXXXX", "$BeginDate", "$EndDate");
                                        timeline.addMetric("ga:pageviews", "Pageviews");
                                        timeline.addMetric("ga:visits", "Visits");
                                        timeline.addMetric("ga:visitors","Vistors");
                                        timeline.setOptions({colors : ['#FF8000', '#7FFF00', '#FF00FE']});
                                        timeline.draw('chart');
                                    });
                                }; 
                            </script>
                            <div id ="esteki_chart" data-oochart='timeline' data-oochart-start-date='$BeginDate' data-oochart-end-date='$EndDate' data-oochart-metrics='ga:pageviews,Pageviews,ga:visits,Visits,ga:visitors,Visitors' data-oochart-profile='XXXXXXXX></div>`

**Comment by mariasoromenho** [comment]
this works for me:

```
<div id='chart'></div>

<script src='../oocharts.js'></script>
<script type="text/javascript">

    window.onload = function(){
        oo.setAPIKey("xx");
        oo.load(function(){

        var timeline = new oo.Timeline("xx", "30d");
        timeline.addMetric("ga:visits", "Visits");
            timeline.addMetric("ga:newVisits", "New Visits");
            timeline.addMetric('ga:pageviews', 'Pageviews');

                timeline.setOptions({colors:['#27A9E3', '#FF6666', '#1ABC9C'],
                chartArea: {left:30,top:20,width:"100%",height:"75%"},       
                fontSize: '11',
                pointSize: 4,
                curveType: 'function',
                legend: {position: 'none'},
                tooltip: {textStyle: {color:"#666"}},
                vAxis:{baselineColor: '#ccc', viewWindowMode: "explicit", viewWindow:{ min: 0 }},
                hAxis: {baselineColor: '#FFFFFF',  gridlines: {count: 2, color:"#FFF"}}
                });

                   timeline.draw('chart');

        });
    };

</script>
```

**Comment by iJohnnyCash** [comment]
I think I found a bug with this function. Below is a very simple example-code. The problem is that for some time appears right chart, but after a while appears default chart. From browser to browser, differs little the bug. 

The code is 
`<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>title</title>
    <script type="text/javascript" src="oocharts.js"></script>
  </head>
  <body>
                        <div style="">
                            <script type="text/javascript">
                            window.onload = function(){
                                oo.setAPIKey("XXX");
                                oo.load(function(){
                                    var timeline = new oo.Timeline("XXX", "30d");
                                    timeline.addMetric("ga:pageviews", "Pageviews");
                                    timeline.addMetric("ga:visits", "Visits");
                                    timeline.addMetric("ga:visitors","Vistors");
                                    timeline.setOptions({legend: {position: 'top', alignment:'center'}});
                                    timeline.draw('chart');
                                });
                                }; 
                            </script>
                            <div id ="chart" data-oochart='timeline' data-oochart-start-date='30d' data-oochart-metrics='ga:pageviews,Pageviews,ga:visits,Visits,ga:visitors,Visitors' data-oochart-profile='XXX'></div>
                        </div>
  </body>
</html>`

You cant find here: 
http://www.e-steki.gr/mediakit/test.html

Here is a small video:
http://www.screencast.com/t/vNrXCXkZtwX

**Comment by tshaddix** [comment]
Hey @iJohnnyCash,

Thanks for pointing this out. From what I am seeing, your problem is actually a problem with the Google Visualization library. OOcharts doesn't do any drawing magic behind the scenes, so it would be an issue with Google Visualization.

The terminology Google uses to describe that section of the chart is a `legend`. I'd start [here](https://www.google.com/search?q=google+visualization+legend+problem)

**Comment by tshaddix** [comment]
I'm going to go ahead and close this. Feel free to make a new issue if something goes wrong on the OOcharts side.
