### ISSUE TITLE
setFilter for Table query doesn't work

### ISSUE THREAD

**Issue by vijayamaharaja** [tshaddix/oocharts-js#3]
Was testing OOcharts - Table object for displaying top viewed pages from my website and noted that <code>table.query.setFilter(filters)</code> function isn't working,

This is the code that I used to fetch data from GA and display in my test page:
<code>var t1=new oo.Table(profileID, "30d");
t1.addMetric('ga:visitors','Visits');
t1.addDimension('ga:pageTitle','Page title');
t1.query.setFilter('ga:pagePath!@partners;ga:pageTitle!@eBugs');
t1.query.setSort('-ga:visitors,ga:pageTitle');
t1.query.setMaxResults(5);
t1.draw('topPage');</code>

As of now, am getting the table populated with Top 5 visited pages, but it doesn't filter out the query provided. 

I got the filter syntax from <a href="https://developers.google.com/analytics/devguides/reporting/core/v3/reference#filterSyntax">here</a>.

On the documentation for Query object, the property/prototype for setting filter was denoted as <code>setFilters(filters)</code> but when I checked on the code, I noticed that its <code>setFilter</code>.

**Comment by tshaddix** [comment]
Thank you. I will update this right away.
