### ISSUE TITLE
oo.setBarDefaults

### ISSUE THREAD

**Issue by damiansmith86** [tshaddix/oocharts-js#30]
I have just noticed whilst testing that setting oo.setBarDefaults() prevents the data from loading.

I have had no issues with Timeline,Table or Pie. Has anyone else come across this issue?

```
    oo.setBarDefaults({
        backgroundColor: 'transparent'
    });
```

In my console I get the following:

Uncaught TypeError: Object #<Object> has no method 'setBarDefaults'

**Comment by tshaddix** [comment]
This should be working now.
