### ISSUE TITLE
Modify returned value

### ISSUE THREAD

**Issue by japborst** [tshaddix/oocharts-js#33]
When requesting values such as `ga:percentNewVisits`, it returns a value that is very accurate, however this means a value with 14 digits is injected. I wondered if it was possible to modify this value before `.draw()`.

This works so far:

```
newVisits.setMetric("ga:percentNewVisits");
newVisits.draw("newVisits");

window.setTimeout(function(){
    newVisits.innerHTML = Math.round(newVisits.innerHTML);
},1500);
```

Unfortunately, that is dependant on the speed of acquiring the data and will show a flash of the long value. Oddly enough, `console.log(newVisits)` returns the object, but `Math.round` on the object without the `setTimeout` does not work...

**Comment by tshaddix** [comment]
If you want to do it this way, you can pass a callback function to the draw:

``` js
newVisits.draw("newVisits", function(){
   newVisitsElement.innerHTML = Math.round(newVisitsElement.innerHTML);
});
```

You can also use a query to interact with the data yourself:

``` js
var query = new oo.Query(profile, "30d");
query.addMetric("ga:percentNewVisits");
query.execute(function(data){
   var rounded = Math.round(data.rows[0][0]);
   newVisitsElement.innerHTML = rounded;
});
```

**Comment by japborst** [comment]
Thanks for the quick reply!

Ah! Didn't know one could parse a function as a second argument. Neat!

Unfortunately though, this does not work (both methods). The value gets rounded, however `newVisits` (or `query`) is not yet the DOM object but a script object from `oocharts.js` so therefore an `innerHTML` does not really work.

**Comment by tshaddix** [comment]
Ah yes, this was hypothetical. I was assuming that somewhere in your code you had created a variable `newVisits` by using the `getElementByID()`. I just looked at your code more closely (sorry about that). You were using `newVisits` as the name of your OO object, not a DOM pointer. My bad!

**Comment by tshaddix** [comment]
_Edit:_ I updated my code example to `newVisitsElement` so as not to be confused by anyone else.

**Comment by tshaddix** [comment]
@japborst can you try using:

``` js
var query = new oo.Query(profile, "30d");
query.addMetric("ga:percentNewVisits");
query.execute(function(data){
   var rounded = Math.round(data.rows[0][0]);
   document.getElementById("newVisits").innerHTML = rounded;
});
```

I believe this should work as long as you have an HTML element with the id "newVisits".

**Comment by japborst** [comment]
@tshaddix sorry for my late reply, been quite busy with some stuff that I hadn't been on GitHub yet. Thanks for the pointers, I will test if this works (very likely will be).

Thanks for all!

**Comment by japborst** [comment]
**update**: that works perfectly, thanks!

I was confused by the fact that after load, the OO object seemed to be a DOM object and I should be able to manipulate that, which I couldn't. Works perfectly now :-)

**Comment by tshaddix** [comment]
@japborst Great! Glad to hear it's working now.

Yes, sorry for the misunderstanding, my bad. Officially: "The OOobject does not magically transform into a DOM object behind the scenes." ;)

**Comment by japborst** [comment]
@tshaddix yeah, it was my weird thinking at the time. Makes no sense in any way that it should do so now.

**Comment by tshaddix** [comment]
@japborst :)
