### ISSUE TITLE
Display time unit (unit in general)

### ISSUE THREAD

**Issue by radaniba** [tshaddix/oocharts-js#35]
Hello 

I am trying to figure out a way of displaying time unit in  

`addMetric( "ga:serverConnectionTime", "Server Connection Time");`

Any idea how to configure that ?

Thanks

**Comment by japborst** [comment]
I suppose the `serverConnectionTime` is in seconds?

You can do a query, format into minutes and put it into the element with id `myId`:

```
var query = new oo.Query(xxxxxxx, 30d);
query.addMetric("ga:serverConnectionTime");
query.execute(function(data){
  sct = data.rows[0][0];
  sct_sec = Math.round(sct%60);
  if(parseInt(sct_sec).toString().length < 2){
    sct_sec = "0" + sct_sec;
  }
  sct_min = Math.round(sct - sct_sec)/60;
  document.getElementById("myId").innerHTML = sct_min + ":" + sct_sec;
});
```

**Comment by tshaddix** [comment]
@japborst Great solution.
