### ISSUE TITLE
problem to see graphs

### ISSUE THREAD

**Issue by zekoto** [tshaddix/oocharts-js#37]
hello,

I am a beginner and so I tried the examples given by oocharts.com (bar.html, etc ...) but when I go on the page http://........../bar . html I have nothing that appears.
I have put my api and my profile id key.

thank you for your help.

the email address "support@oocharts.com" returns an error that the email address does not exist.

Regards

**Comment by tshaddix** [comment]
We no longer offer email support. Thank you for making an issue on GitHub.

Can you include the JS code you are currently using in an email to tyler@tinb.in?
