### ISSUE TITLE
"User is already linked to Google profile" error when trying to connect to Google.

### ISSUE THREAD

**Issue by stevenorell** [tshaddix/oocharts-js#38]
When I initially signed up for OOcharts, I used an account that didn't have any Google Analytics profiles. I then added a profile, but when I try to connect, I get an error message stating "User is already linked to Google profile" and returned to the Connect page.

**Comment by tshaddix** [comment]
@stevenorell I can remove your past account for you. Just send the email address you used to signup to tyler@tinb.in.
