### ISSUE TITLE
Certain dimensions cause a Bad Request

### ISSUE THREAD

**Issue by japborst** [tshaddix/oocharts-js#40]
Hi,

Apparently when using certain dimensions such as `ga:deviceCategory` (https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=platform_or_device&jump=ga_devicecategory), this results in a bad request whilst others (as shown in the example) work perfectly.

code:

```
var table = new oo.Table(profile,dateStart)
     //works
     table.addMetric("ga:visits","Visits");
     table.addDimension("ga:city","City");
     //doesn't work
     table.addMetric("ga:visits","Visits);
     table.addDimension("ga:deviceCategory","Device Category");

     table.draw("rwd");
```

Any clue what's causing this?

Thanks

**Comment by sheck** [comment]
I'm noticing the same problem —  I'd love to be able to use `ga:deviceCategory` as a dimension.

**Comment by sheck** [comment]
Also, I noticed that it only doesn't seem to work for dynamic.json — prebuilt queries seem to be able to use it.

**Comment by tshaddix** [comment]
Hey @sheck @japborst , sorry for the late reply. I've been pretty busy the last couple weeks.

I'm wondering why this is causing an issue. The API uses our ga-validator to make sure the parameters are valid. You can see the validation line [here](https://github.com/OOcharts/ga-validator/blob/master/src/validator.coffee#L240). I can try to take a look later this week on why this might be the case.

**Comment by japborst** [comment]
Hey @tshaddix, that's alright:) Thanks for looking into it. Anything I can test at my end, if various parts work as they should?

**Comment by japborst** [comment]
Can it be the case that it is because `ga:isMobile` changed to `ga:deviceCategory==mobile` and `ga:isTablet` changed to `ga:deviceCategory==tablet`?

**Comment by tshaddix** [comment]
@japborst Most likely! Thanks for bringing this to my attention. So a simple change in the validator project should fix the issues.

**Comment by japborst** [comment]
You mean that that change will not throw back a `bad request`? As `ga:deviceCategory` is still a valid dimension and one would not intend to use `ga:deviceCategory==mobile` (only if you're looking for mobile values, whereas otherwise desktop, tablet and mobile would be fetched).

**Comment by tshaddix** [comment]
Hmmm, now that I'm looking at the validation line, it only checks for existence and does not check the actual value. So it shouldn't be returning a 400... I'll look a little deeper.

**Comment by tshaddix** [comment]
@japborst This should now be working.

**Comment by japborst** [comment]
Oh, this is great! Will test ASAP and let you know. Thanks

**Comment by tshaddix** [comment]
@japborst No problem! Please reopen if it's not working for you.

**Comment by japborst** [comment]
Works beautifully! Props.

**Comment by tshaddix** [comment]
Great! Good luck.
