### ISSUE TITLE
Refresh rate

### ISSUE THREAD

**Issue by kvasa** [tshaddix/oocharts-js#41]
Hi,

First of all I want to Thank Your team for awesome work on oocharts it is a very useful project. I have a one question. You probably store results of my requests if they are same so when I ask for them you just send me this stored data. My question is how often do you refresh this data from Google Analytics?

Sorry I am asking you here, but support@oocharts.com probably does not exist.

Thank You for your answer.

**Comment by tshaddix** [comment]
Hello @kvasa . Yes, our support email was taken offline a little while ago.

To answer your question: We cache your requests for 1 hour. Basically, when you make a request through our API, we store that request and the response from Google in a cache for an hour. That way, if you make the same request again, we don't have to go all the way to Google to respond with the data.
