### ISSUE TITLE
Custom dimensions are not accepted by API

### ISSUE THREAD

**Issue by alexn-ops** [tshaddix/oocharts-js#42]
It seems that API does not accept custom dimensions in both "dimensions" and "filters" parameters, both in API and web interface. API responds with HTTP 400 status code; web interface looks like this:

![image](https://f.cloud.github.com/assets/5923148/2011510/ac2b9690-877b-11e3-9938-517e7a4536e2.png)

By custom dimensions I mean "ga:dimension1", "ga:dimension2" etc.

Also, email "support@oocharts.com" does not work, GMail refuses to deliver emails to it.

**Comment by tshaddix** [comment]
@nevitas Yes, the support email has be decommissioned. The link still needs to be removed from our Mission Control.

I was not aware that Google Analytics allowed custom dimensions in the format. Our API uses our ga-validator project for validations. I've  always seen custom dimensions in [this format](https://github.com/OOcharts/ga-validator/blob/master/src/validator.coffee#L444-L445). Did I miss something?

**Comment by alexn-ops** [comment]
@tshaddix, ga:customVarName(n) and ga:customVarValue(n) are custom variables, and I'm talking about custom dimensions, which are aliased as ga:dimension1, ga:dimension2, ga:dimension3 ... ga:dimension200.

Here are the docs about custom dims: https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets

One more link: this tool allows debugging of Core Data API and it perfectly accepts ga:dimension1 as a dimension value (as long as you have such dimension in your GA account): https://ga-dev-tools.appspot.com/explorer/

**Comment by tshaddix** [comment]
@nevitas Alright, thanks for the links. This pretty much invalidates the existence checking in the ga-validator project. It's crazy to think this didn't come up back in our Alpha testing. Thanks for pointing this out.

**Comment by tshaddix** [comment]
@nevitas I take that back. It doesn't invalidate as it appears these custom dimensions/metrics must be in the format: `dimension[0-9]+`. Is that correct?

**Comment by alexn-ops** [comment]
@tshaddix Yes, that's correct (with `ga:` prefix).

**Comment by tshaddix** [comment]
@nevitas Great. I'll queue those changes.

**Comment by narenana** [comment]
@tshaddix eagerly waiting for the support for custom dimensions... 
I think an addition to your validator code should make it work.

**Comment by tshaddix** [comment]
@nevitas I have added the additions. Still doing some testing before it goes live.

Forgive the response time. I'm doing this as a hobby and I often have things come up that take me away from OOcharts work.

**Comment by tshaddix** [comment]
This now works on the API. Adding a query will still have issues. We are working on resolving this.

**Comment by tshaddix** [comment]
Mission control is now also updated with these changes.
