### ISSUE TITLE
AdSense metrics return 400 Bad Request

### ISSUE THREAD

**Issue by luckyshot** [tshaddix/oocharts-js#43]
Hi guys,

<code>ga:adsenseRevenue</code> and any other AdSense related metrics return a 400 Bad Request. Testing them in their HTML version: 

<pre>&lt;div data-oochart='timeline' 
data-oochart-metrics='ga:visits,Visits,ga:adsenseRevenue,Revenue' 
data-oochart-start-date='7d' 
data-oochart-profile='XXXXXXX'&gt;</pre>

I think the solution is simple, adding these metrics:
https://developers.google.com/analytics/devguides/reporting/core/dimsmets#q=adsense

In the validator file: 
https://github.com/OOcharts/ga-validator/blob/master/src/validator.coffee#L240

Let me know if you need some help testing.

Cheers

**Comment by tshaddix** [comment]
@luckyshot Yep! That should be a simple fix. I'll add it to the queue.

**Comment by luckyshot** [comment]
@tshaddix thanks mate. Do you have an OOcharts changelog somewhere?

**Comment by tshaddix** [comment]
@luckyshot No problem! Right now the "releases" have been serving as a changelog. Any suggestions on what would be a good way to have a dedicated one?

**Comment by tshaddix** [comment]
@luckyshot should be working now.
