### ISSUE TITLE
Loading icon

### ISSUE THREAD

**Issue by jorgeam91** [tshaddix/oocharts-js#44]
A loading icon that users can use on their dashboards to display for whenever their charts are loading. Useful for public displays to let the consumer know their data is being fetched.

**Comment by tshaddix** [comment]
@jorgeam91 This functionality is already available. A spinner is not included by default as we did not want to force our stylistic views upon anyone's site. The `oo.load()` function can be passed a callback function, which can be used to remove a spinner that has been placed.
