### ISSUE TITLE
Converting metrics to integers

### ISSUE THREAD

**Issue by jazelke** [tshaddix/oocharts-js#45]
Hello,

A little background: I'm trying to calculate % change over a time period. When I have the numbers, I can do it fine (as in I understand the formula). However, when I try to calculate it before displaying it, I run into problems. 

So, I tried just displaying the number of visits in my element by using:

```
document.getElementById('num1').innerHTML=num1;
```

instead of

```
num1.draw('num1');
```

The first snippet displays 25134. The second displays [object Object]. If I try parsing the variable as an integer or float, NaN is displayed.

So my question: Is there a way to convert a metric to an integer so that I can perform calculations on it?

Thanks!

**Comment by tshaddix** [comment]
@jeggelke Sure! The best way to do any kind of "custom" action is with the [Query](http://docs.oocharts.com/#query). You can see in the linked documentation that it hands back the raw data from Google. You can parse it there, and then set the element's inner html as you are doing above.

**Comment by jazelke** [comment]
Thanks for the quick reply! So the following code should display the number of visits?

```
var num1 = new oo.Query('{{MYGAPROFILEID}}', '30d');
                num1.addMetric('ga:visits');
                num1.execute(function showNum1(){
                    parseInt(num1, 10);
                    document.getElementById('num1').innerHTML=num1;
                                            });
```

There seems to be something wrong with my syntax, as [object Object] shows up. Any idea on what I am doing wrong?

**Comment by tshaddix** [comment]
@jeggelke Very close! Sorry, should have been more specific. The returned data from Google is a matrix (an array of arrays) which is passed in the callback so in order to access the returned value (in this case it's just 1 value) it would be something like:

``` js

  num1.execute(function (data){
    var _num = parseInt(data[0][0], 10);
    document.getElementById('num1').innerHTML=_num;
  });
```

**Comment by jazelke** [comment]
Thanks so much for your help and patience. Something still seems off. Here is my exact code:

```
<html>
<head>
</head>
<body>

    <div>Visits: <span id='num1'></span></div>
    <script src='/oocharts.js'></script>
    <script type='text/javascript'>

        window.onload = function(){

            oo.setAPIKey('APIKEY');

            oo.load(function(){
                var num1 = new oo.Query('PROFILEID', '30d');
                num1.addMetric('ga:visits');
                num1.execute(function(data){
                    var _num = parseInt(data[0][0], 10);
                    document.getElementById('num1').innerHTML=_num;});
    });
    };
    </script>
</body>
</html>
```

I feel like we are so close, but nothing shows up next to "Visits:" Am I missing something obvious?

**Comment by tshaddix** [comment]
@jeggelke Wish I was near a computer I can debug on. Is there an error in the console window? Can you add a `console.log(_num)` under the line where the integer is parsed? What does it show?

**Comment by jazelke** [comment]
The Chrome Developer console says: "Uncaught TypeError: Cannot read property '0' of undefined". 

Once I expand that, it shows this:

(anonymous function)... oochartSimple.html:20 {my file}
(anonymous function)... oocharts.js:462
callbacks.(anonymous function)... oocharts.js:1022
(anonymous function) and a link to this:

```
JSONP.callbacks.request_0 && JSONP.callbacks.request_0({"total_results":1,"rows":[[25621]],"column_headers":[{"dataType":"INTEGER","columnType":"METRIC","name":"ga:visits"}]});
```

If I remove one of the [0] from the matrix, NaN is displayed. 

Thanks!

**Comment by tshaddix** [comment]
@jeggelke Oh... duh. My bad. You should be accessing data.rows:

``` js
var _num = parseInt(data.rows[0][0], 10);
```

**Comment by jazelke** [comment]
Perfect! Thanks so much for your help! I really appreciate it.

**Comment by tshaddix** [comment]
@jeggelke no problem!

**Comment by jazelke** [comment]
Thanks again for all of your help yesterday. As noted in the original post, I have one last thing that I need to do with my analytics. I need to calculate percent change between two time periods. I was hoping that I could do this: 

```
var num1 = new oo.Query('63292584', '30d');
num1.addMetric('ga:visits');
var num2 = new oo.Query('63292584', '60d');
num2.addMetric('ga:visits');                                        
    num1.execute(function(data){
    var _num = parseInt(data.rows[0][0], 10);
    var num3 = parseInt(num2, 10)+_num; /*This line would use the correct formula for percent change. I'm just using addition as a placeholder*/    
    document.getElementById('numDisplay').innerHTML=num3;                                           
    });
```

My element 'numDisplay' shows NaN and I understand that it is probably because var num3 = parseInt(num2, 10) is not the correct way of doing things, but I can't think of a better way to do it. 

Is it possible to perform math between different queries?

**Comment by tshaddix** [comment]
@jeggelke So the problem here is that you're treating `num2` like it's a number. That's the query object: `var num2 = new oo.Query('63292584', '60d');`. What you will need to do is to wait for both queries to finish:

``` js
var num1 = new oo.Query('63292584', '30d');
num1.addMetric('ga:visits');
var num2 = new oo.Query('63292584', '60d');
num2.addMetric('ga:visits');                                        

// initialize as -1
var _num1Result = -1, _num2Result = -1;

// _done called twice, but only runs inner code if both queries have returned (last time)
var _done = function(){
  if(_num1Result !== -1 && _num2Result !== -1){ // both results have returned
     var num3 = _num2Result +_num1Result; // add results
     document.getElementById('numDisplay').innerHTML=num3;
  }
};

// Execute num1 Query async
num1.execute(function(data){
    var _num1Result = parseInt(data.rows[0][0], 10);
    _done();                                           
});

// Execute num2 Query async
num2.execute(function(data){
    var _num2Result = parseInt(data.rows[0][0], 10);
    _done();                                  
});
```

**Comment by jazelke** [comment]
Sorry, treating num2 as a number was a stupid mistake on my part.
Won't this snippet always return -1 for _num2result (and vice versa), making the if statement false?

```
num1.execute(function(data){
    var _num1Result = parseInt(data.rows[0][0], 10);
    _done();                                     
});
```

I tried this and that looks to be the case: 

```
<html>
<head>
</head>
<body>
    <div><b><u>num1</u></b></div>
    <div>_numResult1: <span id='numDisplay'></span></div>
    <div>_numResult2: <span id='numDisplay2'></span></div>
    <div><b><u>num2</u></b></div>
    <div>_numResult1: <span id='numDisplay3'></span></div>
    <div>_numResult2: <span id='numDisplay4'></span></div>         
    <div><b><u>_done</u></b></div>
    <div>_num3: <span id="numDisplay5"></span></div>
    <script src='/oocharts.js'></script>
    <script type='text/javascript'>

        window.onload = function(){

            oo.setAPIKey('APIKEY');

            oo.load(function(){

var num1 = new oo.Query('GAID', '30d');
num1.addMetric('ga:visits');
var num2 = new oo.Query('GAID', '60d');
num2.addMetric('ga:visits');                                        

// initialize as -1
var _num1Result = -1, _num2Result = -1;

// continue called twice, but only runs inner code if both queries have returned (last time)
var _done = function(){
  if(_num1Result !== -1 && _num2Result !== -1){ // both results have returned
     var num3 = _num2Result +_num1Result; // add results
     document.getElementById('numDisplay5').innerHTML=num3;
  }
};

// Execute num1 Query async
num1.execute(function(data){
    var _num1Result = parseInt(data.rows[0][0], 10);
    _done();
    document.getElementById('numDisplay').innerHTML=_num1Result; 
    document.getElementById('numDisplay2').innerHTML=_num2Result;                                            
});

// Execute num2 Query async
num2.execute(function(data){
    var _num2Result = parseInt(data.rows[0][0], 10);
    _done();
    document.getElementById('numDisplay3').innerHTML=_num1Result; 
    document.getElementById('numDisplay4').innerHTML=_num2Result;                                   
});

});
};
</script>
</body>
</html>
```

I also tried the script without the 'document.getElementById('numDisplay').innerHTML=_num1Result;' parts and had no luck either. I just used those for debugging.

**Comment by tshaddix** [comment]
@jeggelke You're correct, but that's the point :)

The first time `_done` would be called would be when only one of the queries has returned. If this is the case, then you can't perform the necessary calculation. The second time it will be called is when the second query has finished. In this case, we now have both numbers filled and the if statement will pass, letting us make the necessary calculation.

**Comment by tshaddix** [comment]
Can you do a `console.log(_num1Result, _num2Result)` in the body of `_done` before the if statement?

**Comment by tshaddix** [comment]
I made an error in the code above! There should not be new variable being created in the return callback:

``` js
// Execute num1 Query async
num1.execute(function(data){
    var _num1Result = parseInt(data.rows[0][0], 10);
    _done();                                           
});
```

Should be

``` js
// Execute num1 Query async
num1.execute(function(data){
    _num1Result = parseInt(data.rows[0][0], 10); // no 'var' at beginning
    _done();                                           
});
```

The same would go for the `num2.execute()`

**Comment by jazelke** [comment]
Ahhh I get it now. That extra var was the problem. And that makes it work exactly as I need it to! You are the best!

**Comment by tshaddix** [comment]
@jeggelke Glad to hear it's working now! Let me know if you have any more questions.
