### ISSUE TITLE
Timeline with pageviews for a single url

### ISSUE THREAD

**Issue by derekahmedzai** [tshaddix/oocharts-js#46]
How can I show a timeline with pageviews for a single url? For example, just the visits to `/about-us`.

I can show pageviews for the whole site with this

```
timeline.addMetric("ga:pageviews", "Pageviews");
```

But how do I filter by page/url?

**Comment by tshaddix** [comment]
@derekahmedzai You can use a filter to do that:

``` js
timeline.query.setFilter('ga:pagePath==/about-us');
```

**Comment by derekahmedzai** [comment]
Thanks, that works perfectly
