### ISSUE TITLE
Formatting Tooltip Data

### ISSUE THREAD

**Issue by winterjd23** [tshaddix/oocharts-js#47]
Is there a way to format the tooltip data?

For instance, I have a pie chart with revenue by source, and if I hover over, the tooltip will show something like 164753.84 (21.11%).

Is there a way to format that so it would appear as $164,753.84 (21.11%)? I'm not sure how that data is passed to the Google Visualization API, and if there is a way to transform it?

Thanks.

**Comment by tshaddix** [comment]
@winterjd23 sorry for the late response.

If you want to do something custom with the data, I suggest using an OOquery to fetch the data, and then using the Google Visualization API "manually" to build a Pie chart with the data.

**Comment by winterjd23** [comment]
Ah gotcha, I was afraid that would be the answer!  I was hoping you had some hidden feature that would enable an easy switch. Haha

Thanks though!

**Comment by tshaddix** [comment]
@winterjd23 Sorry about that! I wish we did as well :+1:
