### ISSUE TITLE
Using multiple filters in a query

### ISSUE THREAD

**Issue by jazelke** [tshaddix/oocharts-js#49]
Hello. Do you know how I can use multiple filters in a query? When I try doing something like this: 

```
var past2Months = new oo.Query(chartID, previousMonth, lastMonth);
past2Months.addMetric(gaParameter);
past2Months.setFilter('ga:visitorType=@new', 'ga:pagePathLevel1=@/example/');
```

 the second filter is applied to it. I've tried switching the filters around, and the second filter is always applied. 

Any help would be appreciated.

**Comment by tshaddix** [comment]
@jeggelke The `setFilter` method takes in a single string as an argument. You would combine them to be something like: `setFilter('ga:visitorType=@new;ga:pagePathLevel1=@/example/')`.

**Comment by jazelke** [comment]
That works as it should. I swear that was the first thing that I tried but it didn't work before... Anyway, as always, thanks a lot for your help!

**Comment by tshaddix** [comment]
Glad to hear it!
