### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by progcode** [tshaddix/oocharts-js#50]
hello,

I have linked my Google account to OOcharts and was provided with an API key.
I have added this API key, as well as my account ID but get the following error:

JSONP.callbacks.request_0 && JSONP.callbacks.request_0({"error":"Invalid param {key}: API Key is invalid"});

**Comment by tshaddix** [comment]
Are you, by chance, including the `{{` and `}}`?

**Comment by progcode** [comment]
yeah

oo.setAPIKey("{{ apikey }}");

**Comment by tshaddix** [comment]
Go ahead and remove those: `oo.setAPIKey("apikey");`

**Comment by progcode** [comment]
not working the issue is same

**Comment by tshaddix** [comment]
Go ahead and send  the script you're using to tyler@tinb.in. I can help you that way.
