### ISSUE TITLE
Unlimited requests

### ISSUE THREAD

**Issue by vmandrak** [tshaddix/oocharts-js#53]
Hi there. First of all congrats on your amazing project! It saved my life. Is there a way to have unlimited requests per month and if so how much would it cost?

**Comment by tshaddix** [comment]
Hey @vmandrak!

Glad to hear OOcharts is working well for you. We are limited in the number of requests that our app can send per day because of Google's API restrictions. If you're going to be using a system like this heavily, you may want to look into just hooking straight into Google's API rather than using OOcharts. If I can recall correctly, the initial limit is 50k per day (quite a bit).

**Comment by vmandrak** [comment]
Thank you for your quick response. I appreciate it.

**Comment by tshaddix** [comment]
@vmandrak you're welcome!

**Comment by RyanPaiva56** [comment]
Why not collect API keys from us as well and use that instead of your own? Like, to increase the limit from 10k, we pay $5 per month and supply a Google API Key.

**Comment by tshaddix** [comment]
Not a bad idea.

The initial reason was to limit the amount of work for users to connect their GA account. Have you looked at [OOcharts Server](http://server.oocharts.com/)? If you feel confident enough, you could just run your own OOcharts server and not even worry about our service limitations.

The server version is alpha, but it might be worth a shot to check out.

**Comment by RyanPaiva56** [comment]
I guess why bother decentralizing when you can just have this single hub handle all of the maintenance and make money at the same time? I'd rather pay monthly for a service that I can rely on than having to maintain my own version of the service.

**Comment by tshaddix** [comment]
Interesting. We've heard the "I'd rather pay comment" a lot lately. I'll make this part of our next meeting.

The server release was more for people who wanted to be completely private and also modify the source as they see fit.
