### ISSUE TITLE
Profile ID and API Key help

### ISSUE THREAD

**Issue by showcasefloyd** [tshaddix/oocharts-js#55]
I'm trying to set up a simple chart to use on my company's website but I can't I'm confused.

First I can't seem to find my Google Profile ID in the latest Google Analytics Suite?

And second what API Key is OOCharts looking for exactly? Am I supposed to turn something on in Google to get this API key? Do I need to enable the Analytics API (or is this not needed)? Also in your examples you have two places for API keys? In the example are these the same key? And do these keys differ from the Transaction API Keys that you set up in Mission Control. Please I need some explanation here. Thanks

Thanks so much in advance.

Floyd

**Comment by showcasefloyd** [comment]
Sorry I figured it out.

**Comment by tshaddix** [comment]
@showcasefloyd no problem! Sorry I couldn't get to your question sooner.
