### ISSUE TITLE
Multiple APIs on the same page

### ISSUE THREAD

**Issue by showcasefloyd** [tshaddix/oocharts-js#56]
I need to pull data from three different APIs, but onto the same page.

So for instance if I want to have a chart for each of my current websites.

Is there an example of how to this? I only see and example of how to set up one API per page right now.

Thanks so much in advance,

Floyd

**Comment by tshaddix** [comment]
Sure! Just add all of those profiles under one API Key on OOcharts Mission Control. Then, when you're building the page change the profile id to whatever chart you want to display information for The single API key should cover all of the requests because you have registered them with us.

**Comment by showcasefloyd** [comment]
Oh that's a much better solution then what I cam up with. I actually made three separate pages and pulled them in via iFrames three different iFrames

Okay, thanks for the heads up.

Floyd

**Comment by tshaddix** [comment]
No problem! Good luck.
