### ISSUE TITLE
Change Cache Time?

### ISSUE THREAD

**Issue by winterjd23** [tshaddix/oocharts-js#57]
Hi there-

Was wondering if there is a way to adjust how long the data is cached? For instance, I have a lot of charts that are showing last 14 days ending yesterday. That data only needs to be pulled once a day, not every hour.

Is this possible?

**Comment by tshaddix** [comment]
@winterjd23 Not at this time. We rely on our DB to drop table entries based on timestamp and fixed cache time. Not the most flexible solution, I know. Definitely might look into flexible caching in the future.

**Comment by winterjd23** [comment]
Right on, understandable.

Related question: what happens if I go over 10k transactions in a month?

**Comment by tshaddix** [comment]
@winterjd23 You will no longer be able to use OOcharts for that month :(

We've considered adding ways to increase limits and priority, but life/projects have got in the way recently. Definitely a possibility in the future!
