### ISSUE TITLE
Filters not working in specific case

### ISSUE THREAD

**Issue by tshaddix** [tshaddix/oocharts-js#6]
``` js

var m = new oo.Metric(profile, start, end);
m.setMetric(metric, label);
//m.query.setFilter('filterString'); Gives same result with or without this line
m.draw("met");              
```

**Comment by vijayamaharaja** [comment]
@tshaddix any luck on this issue?

**Comment by tshaddix** [comment]
Sorry @vijayamaharaja , busy week. I will look into it shortly.

**Comment by tshaddix** [comment]
@vijayamaharaja I have determined this is an issue with the API endpoint for Dynamic queries. Something didn't tie up like it was supposed to from the query endpoint.

**Comment by tshaddix** [comment]
@vijayamaharaja I have pushed the changes live. Let me know if it isn't working for you. Just a note, any queries you did in the last hour are cached so if you use the same parameters as a previous query you will get the same data as before. So try changing the date range by 1  or 2 days to confirm it is working.
