### ISSUE TITLE
How can I group results by month?

### ISSUE THREAD

**Issue by RyanPaiva56** [tshaddix/oocharts-js#60]
I'm using timeline and when I do a 12m to show a timeline of the last year, it gives me data points per day which is hard to read. I'd like to group them by month. How can I do that?

Here's my SO post: http://stackoverflow.com/questions/24580088/oocharts-monthly-timeline

**Comment by tshaddix** [comment]
You can do this by using a custom [Query](http://docs.oocharts.com/#query-1) and then building a line chart with the included Google Visualization package.

There is a feature request for including this functionality in the OOcharts script #17

**Comment by RyanPaiva56** [comment]
Thanks, I'll give this a shot. Feel free to xpost on my SO post if you want some sweet SO points.

**Comment by tshaddix** [comment]
@golevel Haha I may have some extra time later today to post a full answer/example on SO. I need to make sure to earn those sweet sweet SO points.

**Comment by RyanPaiva56** [comment]
I can create the query I need but I'm not sure how to make a custom line graph. Where is the documentation for that? Is it the same as the timeline?

**Comment by RyanPaiva56** [comment]
I just gave it ago with google visualization in my callback function and it worked, to a point. When I run chart.draw(data, options); it gives me this error:

"You called the draw() method with the wrong type of data rather than a DataTable or DataView"

I checked the output and the output is accurate, just maybe not in the format that they want?

**Comment by tshaddix** [comment]
Data from OOcharts must be turned into a DataTable.

Take a look at the [Source](https://github.com/OOcharts/js/blob/master/oocharts.js#L650-L681). Is that helpful?

**Comment by RyanPaiva56** [comment]
Thanks, yes that does make sense. Is there a way for me to reuse one of the existing functions or do I need to create my own? I'm just graphing pageviews by month.

**Comment by tshaddix** [comment]
No problem!

Which functions were you hoping to reuse? I think I only have the parse/format date functions exported out which wouldn't be helpful for a per month chart. Any suggestions would be appreciated.

**Comment by RyanPaiva56** [comment]
No worries. I'm not a js expert but I'll give it a shot and post up the code here if it works.

**Comment by tshaddix** [comment]
Sounds great! Let me know if you run into some blockers.

**Comment by RyanPaiva56** [comment]
Worked great! I just did the oocharts query and the google charts visualization from their API in the callback function. Thanks!

**Comment by tshaddix** [comment]
This is great to hear! Will you be answering your SO post? I think this is good content to have linked in the issues.

**Comment by RyanPaiva56** [comment]
Yup! I'll post up my code.
