### ISSUE TITLE
Core Reporting API v3

### ISSUE THREAD

**Issue by curtisblackwell** [tshaddix/oocharts-js#61]
First, I think there should be a link in the docs to Google's [Core Reporting API](https://developers.google.com/analytics/devguides/reporting/core/dimsmets) so that Oocharts users know the available metrics.

Second, it seems like OOcharts uses the deprecated API. I can't use `ga:bouceRate`, but I can use `ga:visitBounceRate`, which is deprecated.

What steps would it take to use the newer version? I'd be happy to contribute with a little guidance. I know some things in the docs would need updating, like `ga:visits` -> `ga:users`.

**Comment by tshaddix** [comment]
Good ideas @curtisblackwell 

I am behind in updating the [validator](https://github.com/OOcharts/ga-validator) to the new specs. Updating that project to the new dims & mets will also update the API.

**Comment by curtisblackwell** [comment]
It looks like it'd just mean updating the values in all of the `addMetric` and `addDimension` calls in lines 153-469 of [validator.coffee](https://github.com/OOcharts/ga-validator/blob/master/src/validator.coffee) and possibly adding some new ones, is that right?

**Comment by tshaddix** [comment]
That's it! Pretty simple, but it saves us from wasting our Google Transaction limits on simple mistakes like bad metrics.

**Comment by curtisblackwell** [comment]
Sweet, that's pretty simple. I'll try to make time for that this/next week.
