### ISSUE TITLE
City Visits in query

### ISSUE THREAD

**Issue by carlgordon** [tshaddix/oocharts-js#62]
Hi, I am trying to get the visits number for a filtered City. I have no problem with using it in tables but I need just the number. This what I have so far...

```
        var ctv = new oo.Query('{{myGAID}}', '30d');
        ctv.addMetric("ga:visits");
        ctv.addDimension("ga:city");
        ctv.query.setFilter('ga:city==Cape Town');
                    ctv.draw('metric');
```

Thanks

Carl

**Comment by tshaddix** [comment]
Hello,

Is it a requirement that the filter attribute be part of the request (do you have to request a `ga:city` dimension in order to filter by `ga:city`)? I can't remember at the moment.
