### ISSUE TITLE
ga:users is not a valid metric

### ISSUE THREAD

**Issue by fabionapodano** [tshaddix/oocharts-js#65]
Hi, I normally use OOCharts with success, so any configuration issue is excluded.

i have tried to perform a query like this:

https://api.oocharts.com/v1/dynamic.jsonp?key={{ MYKEY }}&profile={{ MYPROFILE }}&metrics=ga%3Ausers&start=30d&end=2014-09-23&callback=JSONP.callbacks.request_0

but I get the following error:

JSONP.callbacks.request_0 && JSONP.callbacks.request_0({"error":"Invalid param {metrics}: ga:users is not valid metric"});

however, ga:users is a valid GA metric, as shown here:

https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=user&jump=ga_users

the exacts same query with ga:visits instead of ga:users works

what am I missing?

**Comment by tshaddix** [comment]
Hi @fabionapodano,

The [validator](https://github.com/OOcharts/ga-validator) under OOcharts has not been brought up to the most recent GA spec. There is a [pull request](https://github.com/OOcharts/ga-validator/pull/11) for adding these metrics which looks complete with the new versions, but does not include the deprecated mets & dims. I have not had the time yet to go through and re-add all of these deprecated tags.

I may have to just force some time aside to manually re-add everything, or I may just remove the entire validator and let Google Analytics do the validation.

**Comment by tshaddix** [comment]
Should be working now.

**Comment by fabionapodano** [comment]
it is indeed working perfectly, many thanks for your quick support!

**Comment by tshaddix** [comment]
No problem!
