### ISSUE TITLE
oochats website offline

### ISSUE THREAD

**Issue by oitsuki** [tshaddix/oocharts-js#69]
Since some day, I don't see anything on charts (oochart). The website seems offline.
There is a consequence ?

**Comment by tshaddix** [comment]
Hi @oitsuki . It was announced a couple times to all users a little over a month ago that we will no longer be hosting the service. You can read about it here: https://medium.com/@tylershaddix/tin-bin-is-moving-on-from-oocharts-59074c7978ff

Not to worry though! We have a self-host solution available. Read about it here: https://www.dropbox.com/s/66svn7wqub0oxhk/edge.mp4?dl=0

I will be getting documentation for this soon.
