### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by mariasoromenho** [tshaddix/oocharts-js#70]
Hi,

I was able to install the OOcharts server and it seems to be running (http://mariasoromenho.com/api/dynamic.jsonp) but everytime i try to call the API from js i receive a 500 Internal Server Error - http://mariasoromenho.com/api/dynamic.jsonp?key=AAAAA1111111BBBBBBCCCCCCC&profile=20754375&metrics=ga%3Avisitors&start=2014-11-06&end=2014-11-13&callback=JSONP.callbacks.request_0

We are using Digital Ocean.

Any idea what this can be?

thank you so much!

**Comment by tshaddix** [comment]
Hey!

No problem. Do you have access to the logs of the server? That should give a little more detail.

**Comment by mariasoromenho** [comment]
Logs are not showing much... Here's a copy - http://pastebin.com/raw.php?i=BPyuHud6#

**Comment by tshaddix** [comment]
Alright, must be coming back from Google. I'll push a change so we can see what's going on.

**Comment by mariasoromenho** [comment]
Yeah, we just realised that too. Here's the error 
{ errors: 
   [ { domain: 'global',
       reason: 'countryBlocked',
       message: 'This service is not available from your country' } ],
  code: 403,
  message: 'This service is not available from your country' }

We'll try to fix it by transfering the droplet to another zone.

**Comment by tshaddix** [comment]
Not too much I can do about that other than make the errors more readable!
Thanks for bringing this up!
