### ISSUE TITLE
Setting up oocharts server

### ISSUE THREAD

**Issue by mbarela82** [tshaddix/oocharts-js#72]
I loved the service that you provided. I'm sorry that you had to shut down. Is there a way to set up the server on my own host?

**Comment by tshaddix** [comment]
There sure is! The repository is [here](https://github.com/tshaddix/oocharts-server). I haven't finished the formal documentation, but I do have a rough screencast available here:

https://www.dropbox.com/s/notapevsb8imj85/edge.mp4?dl=0

**Comment by mbarela82** [comment]
Thank you!!

**Comment by tshaddix** [comment]
No problem! Please ask when you come across any issues!
